name: Run Tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Composer dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Run Tests
      run: |
        echo "::add-matcher::.github/phpunit-problem-matcher.json"
        ./vendor/bin/phpunit --teamcity test
