name: Run Tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Composer dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Configure matchers
      use: ./.github/actions/
    - name: Run Tests
      run: ./vendor/bin/phpunit --teamcity test
